-- =====================================================
-- 01_infrastructure.sql : entrepôt NYC_TAXI
-- Rejouable : peut être relancé sans erreur ni doublon
-- =====================================================

-- 1. Calcul et stockage : SYSADMIN
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
-- IF NOT EXISTS ne modifie pas un warehouse existant : on force les réglages
ALTER WAREHOUSE NYC_TAXI_WH SET WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;

CREATE DATABASE IF NOT EXISTS NYC_TAXI;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI.MARTS;

-- 2. Rôle des outils et ses droits : SECURITYADMIN
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS TRANSFORMER;
GRANT ROLE TRANSFORMER TO ROLE SYSADMIN;   -- hiérarchie : SYSADMIN garde la main

GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE NYC_TAXI TO ROLE TRANSFORMER;

-- RAW : charger des fichiers
GRANT USAGE, CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA NYC_TAXI.RAW TO ROLE TRANSFORMER;
-- Autres couches : transformer
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.STAGING      TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.INTERMEDIATE TO ROLE TRANSFORMER;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA NYC_TAXI.MARTS        TO ROLE TRANSFORMER;

-- 3. Utilisateur de service (sa clé publique sera ajoutée à l'étape 3)
CREATE USER IF NOT EXISTS AIRFLOW_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = TRANSFORMER
  DEFAULT_WAREHOUSE = NYC_TAXI_WH
  DEFAULT_NAMESPACE = NYC_TAXI.RAW
  COMMENT = 'Utilisateur de service pour le script Python et Airflow';
GRANT ROLE TRANSFORMER TO USER AIRFLOW_SVC;

-- Pour tester le rôle soi-même dans Snowsight (remplacer par ton identifiant)
GRANT ROLE TRANSFORMER TO USER MWKKA;